name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Packages
        run: npm ci
      - name: Create Environment File
        run: | 
          mkdir src/environments && echo "${{ secrets.ENV_FILE }}" > /src/environments/environment.development.ts
      - name: Build
        run: npm run build --if-present
      - name: Test
        run: npm test
