name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Packages
        run: npm ci
      - name: Create Environment File
        run: | 
          mkdir \home\runner\actors-workshop\actors-workshop\src\environments 
          echo "${{ secrets.ENV_FILE }}" > \home\runner\work\actors-workshop\actors-workshop\src\environments\environment.development.ts 
          echo "${{ secrets.ENV_FILE }}" > \home\runner\work\actors-workshop\actors-workshop\src\environments\environment.ts 
          ([ -f /src/environments/environment.development.ts ] && echo "file exists")
      - name: Build
        run: npm run build --if-present
      - name: Test
        run: npm test
